# Generated by Django 3.2.7 on 2024-12-29 06:24

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/files/', validators=[services.models.validate_file_extension]),
        ),
    ]
